services:
  backend:
    build:
      context: ./backend
    container_name: backend_app_dev
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/proyecGCV
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend_app_dev
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_db_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: proyecGCV
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
